### PR TITLE
QA Test #1

### PR DESCRIPTION
**Pull request by lilasymons**
Some stuff still needs to be done, but sending this for QA/Font Bakery.

### CODE REVIEW

**Comment by lilasymons** [comment]
@vv-monsalve is this what you all need?

**Comment by vv-monsalve** [comment]
@lilasymons This is great! 

> @vv-monsalve is this what you all need?

Almost! Only that it should be done to the `dev` branch instead of the master so that we don't affect yet the current stable version of the font and source file.

Screen Shot 2022-11-11 at 14 17 23

**Comment by vv-monsalve** [comment]
> you'll need to sign a Contributor License Agreement (CLA).

This is a warning over you need to Sign the [Google CLA](https://opensource.google/documentation/reference/cla). Following the link you can have more details.

**Comment by vv-monsalve** [comment]
Closing this here in favour of #10

**Pull request closed without merging**
